<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Laporan Penjualan</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 11px; color: #1e293b; }
        h1 { text-align: center; font-size: 20px; margin-bottom: 4px; color: #0f172a; }
        .subtitle { text-align: center; color: #64748b; margin-bottom: 20px; font-size: 12px; }
        .summary { display: flex; margin-bottom: 20px; }
        .summary-box { display: inline-block; width: 30%; text-align: center; padding: 10px; margin: 0 1%; background: #f1f5f9; border-radius: 6px; }
        .summary-box .label { font-size: 10px; color: #64748b; text-transform: uppercase; }
        .summary-box .value { font-size: 16px; font-weight: bold; color: #0f172a; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background: #3b82f6; color: #fff; padding: 8px 6px; text-align: left; font-size: 10px; text-transform: uppercase; }
        td { padding: 7px 6px; border-bottom: 1px solid #e2e8f0; }
        tr:nth-child(even) { background: #f8fafc; }
        .text-right { text-align: right; }
        .footer { text-align: center; margin-top: 20px; font-size: 9px; color: #94a3b8; }
    </style>
</head>
<body>
    <h1>📊 Laporan Data Penjualan</h1>
    <p class="subtitle">Dicetak pada: {{ now()->format('d M Y, H:i') }} WIB</p>

    <div style="text-align:center; margin-bottom:20px;">
        <div class="summary-box">
            <div class="label">Total Transaksi</div>
            <div class="value">{{ number_format($totalTransaksi) }}</div>
        </div>
        <div class="summary-box">
            <div class="label">Total Penjualan</div>
            <div class="value">Rp {{ number_format($totalPenjualan, 0, ',', '.') }}</div>
        </div>
        <div class="summary-box">
            <div class="label">Rata-rata / Transaksi</div>
            <div class="value">Rp {{ number_format($rataRataPenjualan, 0, ',', '.') }}</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Tanggal</th>
                <th>Produk</th>
                <th>Kategori</th>
                <th class="text-right">Jumlah</th>
                <th class="text-right">Harga</th>
                <th class="text-right">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($penjualans as $index => $p)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $p->tanggal->format('d/m/Y') }}</td>
                <td>{{ $p->produk }}</td>
                <td>{{ $p->kategori }}</td>
                <td class="text-right">{{ number_format($p->jumlah) }}</td>
                <td class="text-right">Rp {{ number_format($p->harga, 0, ',', '.') }}</td>
                <td class="text-right">Rp {{ number_format($p->total, 0, ',', '.') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        &copy; {{ date('Y') }} — Dashboard Analitik Penjualan | Generated by Laravel DomPDF
    </div>
</body>
</html>
